plugins {
    id 'joid-java'
}

def os = System.getProperty('os.name').toLowerCase()
def arm = System.getProperty('os.arch').startsWith('aarch64')
def lwjglNatives = os.contains('win') ? 'natives-windows' : os.contains('mac') ? (arm ? 'natives-macos-arm64' : 'natives-macos') : (arm ? 'natives-linux-arm64' : 'natives-linux')

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

dependencies {
    compileOnly(files(rootProject.file("libs/joid-core-${joid_version}-dev.jar")))
    compileOnly(files(rootProject.file("libs/joid-base-glfw-${joid_version}.jar")))
    compileOnly(files(rootProject.file("libs/joid-base-openal-${joid_version}.jar")))
    compileOnly(files(rootProject.file("libs/joid-tool-testkit-${joid_version}.jar")))
    compileOnly("javax.vecmath:vecmath:${vecmath_version}")

    testImplementation(files(rootProject.file("libs/joid-core-${joid_version}-dev.jar")))
    testImplementation(files(rootProject.file("libs/joid-tool-testkit-${joid_version}.jar")))
    testImplementation("org.lwjgl:lwjgl:${shaderc_lwjgl_version}")
    testImplementation("org.lwjgl:lwjgl-shaderc:${shaderc_lwjgl_version}")
    testRuntimeOnly("org.lwjgl:lwjgl:${shaderc_lwjgl_version}:${lwjglNatives}")
    testRuntimeOnly("org.lwjgl:lwjgl-shaderc:${shaderc_lwjgl_version}:${lwjglNatives}")
    testImplementation("junit:junit:${junit_version}")
    testRuntimeOnly("commons-io:commons-io:${commons_io_version}")
}

test {
    useJUnit()
    systemProperty('joid.config', layout.buildDirectory.dir('config').get().asFile.absolutePath)
    testLogging {
        exceptionFormat = 'full'
        events('failed')
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}
