plugins {
    id 'joid-java'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

dependencies {
    compileOnly(project(':base'))
    compileOnly(files(rootProject.file("libs/joid-core-${joid_version}-dev.jar")))
    compileOnly(files(rootProject.file("libs/joid-glfw-${joid_version}.jar")))
    compileOnly(files(rootProject.file("libs/joid-testkit-${joid_version}.jar")))
    compileOnly("javax.vecmath:vecmath:${vecmath_version}")
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}
