plugins {
    id 'multiloader-common'
    id 'com.gradleup.shadow'
}

configurations {
    commonJava {
        canBeResolved = true
    }
    commonResources {
        canBeResolved = true
    }
    shade
    joidProd
    joidDev
    implementation.extendsFrom(shade)
    compileOnly.extendsFrom(joidDev)
    runtimeOnly.extendsFrom(joidDev)
}

dependencies {
    compileOnly(project(':common')) {
        def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
    commonJava(project(path: ':common', configuration: 'commonJava'))
    commonResources(project(path: ':common', configuration: 'commonResources'))
    joidProd(files(rootProject.file("libs/joid-core-${joid_core_version}-prod.jar")))
    joidDev(files(rootProject.file("libs/joid-core-${joid_core_version}-dev.jar")))
    shade("javax.vecmath:vecmath:${vecmath_version}")
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

jar {
    archiveClassifier = 'slim'
}

shadowJar {
    configurations = [project.configurations.shade, project.configurations.joidProd]
    archiveClassifier = ''
    exclude('module-info.class', 'META-INF/versions/*/module-info.class')
}
