plugins {
    id 'joid-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()}"
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file('runs/client'))
        }
        data {
            clientData()
            gameDirectory = this.mkdir(this.file('runs/data'))
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            this.file('runs/server').createParentDirectories()
            gameDirectory = this.mkdir(this.file('runs/server'))
        }
        gameTestServer {
            type = 'gameTestServer'
            gameDirectory = this.mkdir(this.file('runs/gameTestServer'))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

configurations {
    additionalRuntimeClasspath.extendsFrom(embed, joidDev)
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

tasks.named('eclipse') {
    dependsOn('neoForgeIdeSync')
    doLast {
        def folders = [':common'].collect { path -> "${mod_id}%%" + project(path).file('bin/main').absolutePath.replace('\\', '\\\\') }
        fileTree('.eclipse/configurations') { include('*.launch') }.each { launch ->
            launch.text = launch.text.replaceAll(/(-Dfml\.modFolders=[^ "]+)/) { all, modFolders -> ([modFolders] + folders).join(File.pathSeparator) }
        }
    }
}
